# at https://docs.docker.com/compose/compose-file/
version: '3.3'
services:
  web:
    container_name: red-packet-api
    image: registry.cn-beijing.aliyuncs.com/btc-com/pushtx:red-packet
    restart: always
    volumes:
      - ./logs:/work/app/logs
    ports:
      - "11111:3000"
    environment:
      # BCH_NETWORK : "testnet"
      BCH_NETWORK : "bitcoin"
      API: "btc.com"
      NODE_ENV: "production"
      # API: "blocktrail"
  web_two:
    container_name: red-packet-api-two
    image: registry.cn-beijing.aliyuncs.com/btc-com/pushtx:red-packet
    restart: always
    depends_on:
      - web
    volumes:
      - ./logs:/work/app/logs
    ports:
      - "11112:3000"
    environment:
      # BCH_NETWORK : "testnet"
      BCH_NETWORK : "bitcoin"
      API: "btc.com"
      NODE_ENV: "production"
  web_three:
    container_name: red-packet-api-three
    image: registry.cn-beijing.aliyuncs.com/btc-com/pushtx:red-packet
    restart: always
    depends_on:
      - web_two
    volumes:
      - ./logs:/work/app/logs
    ports:
      - "11113:3000"
    environment:
      # BCH_NETWORK : "testnet"
      BCH_NETWORK : "bitcoin"
      API: "btc.com"
      NODE_ENV: "production"